### PR TITLE
Updated prop `version` default to: `v9.0`

### PR DESCRIPTION
**Pull request by M1CK431**
V6.0 will be unusable starting on February 8, 2021

### CODE REVIEW

**Comment by M1CK431** [comment]
Hi @adi518 ,

I just discover that the default version (v6.0) will become unusable very soon (on February 8, 2021).
In addition (I don't known why) but passing `version` through `props` to `VFBLogin` component seems ignored.
Because we urgently need to upgrade from v6.0, I have open this PR.

Could we please merge & release asap?
Thanks in advance.

**Comment by adi518** [comment]
Let's fix both issues.

**Comment by M1CK431** [comment]
> Let's fix both issues.

Do you mean that you will fix (and release) both issues before February 8, 2021 or are you expecting a fix from my side?

I'm asking that because we need to deploy a hotfix release tomorrow morning and unfortunately I haven't any time to debug the ignored `version` prop issue right now :disappointed: That's why I have open this PR with only the updated default `version` prop.

**Comment by adi518** [comment]
I'm working on it.

**Comment by adi518** [comment]
I just tested the latest version and the version parameter is passed just fine. Which version are you on?

**Comment by M1CK431** [comment]
> I just tested the latest version and the version option is passed-through just fine. Which version are you on?

I'm using the latest release (v3.0.0) but I just notice that I have two `VFBLogin` component on the same page and pass the `version` option to only one them, then inspect the other one :facepalm: 

I'm really sorry for the noise. I guess I should drink less...

Still, the default version could be upgraded but there is nothing urgent right now.
Anyway thanks a lot for your time and reactivity :kissing_heart: :hugs:

**Comment by adi518** [comment]
I just released `4.0.0`, which replaces the alt logo and upgrades the default graph API version to the latest.

**Pull request closed without merging**
